api_version: 2
defaults:
  update_external_dependencies: true
  auto_merge: true
  allowed_semver_bumps:
    - patch
    - minor
overrides:
  - dependency: rails
    allowed_semver_bumps:
      - patch
  - dependency: google-cloud-discovery_engine
    auto_merge: false
  - dependency: google-cloud-discovery_engine-v1beta
    auto_merge: false
